#####################################################################################
# 시스템별 Properties
#####################################################################################
############################################################
# Server Session Timeout(단위:Second) - 10시간
############################################################
server:
  servlet:
    session:
      timeout: 36000

############################################################
# Spring 설정
############################################################
spring:
  ############################################################
  # view Template(JxlsDownloadView) - Jxls Download view
  ############################################################
  jxls:
    template:
      path: templates/jxls

  ############################################################
  # MVC Configuration
  ############################################################
  #mvc:
  #  view:
  #    prefix: /WEB-INF/views/
  #    suffix: .jsp
  #  static-path-pattern: /**

############################################################
# Application 설정
############################################################
aetem:
  ############################################################
  # Session Duplication Configuration(true:허용/false:허용않함)
  ############################################################
  session:
    duplication: true

  ############################################################
  # Static Resource Configuration
  ############################################################
  view:
    static:
      ko:
      vn:

  ############################################################
  # Application URL Configuration
  ############################################################
  api-gateway:
    url: http://localhost:23025


  ############################################################
  # Application Path Configuration
  ############################################################
  upload:
    root:
    link:
      url:

  ############################################################
  # Image Server Configuration
  ############################################################
  imageServer:
    url:


